version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo ENV vars $BASE_OS $BASE_OS_TAG $APP_PATH $APP_GROUP $APP_USER= $RUBY_VERSION $APPGEMSET
      - docker build  --build-arg  BASE_OS=$BASE_OS
                      --build-arg  BASE_OS_TAG=$BASE_OS_TAG
                      --build-arg  APP_PATH=$APP_PATH
                      --build-arg  APP_GROUP=$APP_GROUP
                      --build-arg  APP_USER=$APP_USER
                      --build-arg  RUBY_VERSION=$RUBY_VERSION
                      --build-arg  APPGEMSET=$APPGEMSET
                      -t $IMAGE_REPO_NAME .


      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
